// Generated by Wrangler by running `wrangler types`

interface Env {
  R3PLY_USER_CONFIGS: KVNamespace
  EMAIL_MAX_BYTES_DEFAULT: 26214400
  EMAIL_HASH_PEPPER_VERSION: '1.0.0'
  R3PLY_DB: D1Database
  MODERATOR_EMAIL: SendEmail
}
declare module '*.toml' {
  const value: string
  export default value
}
declare module '*.eml?raw' {
  const value: string
  export default value
}
