// Generated by Wrangler by running `wrangler types`

interface Env {
	EMAIL_MAX_BYTES_DEFAULT: 26214400;
	EMAIL_HASH_PEPPER_VERSION: "1.0.0";
	EMAIL_HASH_PEPPER: string;
	R3PLY_GIST_TOKEN: string;
	RUNNING_LOCALLY: string;
	HMAC_SECRET: string;
	GITHUB_APP_PW: string;
	R3PLY_DB: D1Database;
	MODERATOR_EMAIL: SendEmail;
}
declare module "*.toml" {
	const value: string;
	export default value;
}
declare module "*.eml?raw" {
	const value: string;
	export default value;
}