#:schema https://unpkg.com/wrangler@4.42.0/config-schema.json

name = "r3ply-cloudflare-worker"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-12-07"

[observability]
enabled = true

[define]
"import.meta.vitest" = "false"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
[vars]
EMAIL_MAX_BYTES_DEFAULT = 26214400 # Cloudflare limits emails to 25MB

[[ratelimits]]
name = "API_RATE_LIMITER_UNAUTHENTICATED"
# An identifier you define, that is unique to your Cloudflare account.
# Must be an integer.
namespace_id = "1001"
# Limit: the number of tokens allowed within a given period in a single
# Cloudflare location
# Period: the duration of the period, in seconds. Must be either 10 or 60
simple = { limit = 12, period = 60 }
# Limits comments via email to 5 emails/60 s/email address
[[ratelimits]]
name = "COMMENT_VIA_EMAIL_RATE_LIMITER"
namespace_id = "1002"
simple = { limit = 5, period = 60 }
# Limits access to the "email interface" to 5 emails/60 s/email address
[[ratelimits]]
name = "EMAIL_INTERFACE_RATE_LIMITER"
namespace_id = "1003"
simple = { limit = 5, period = 60 }

# The following is needed for CF pages + D1 local development
# [Cloudflare Docs](https://developers.cloudflare.com/d1/learning/local-development/)
[[d1_databases]]
binding = "R3PLY_DB"                                 # Should match preview_database_id
database_name = "r3ply"
database_id = "24e83108-b6d9-45b0-9744-4b53a4021511" # wrangler d1 info YOUR_DATABASE_NAME
preview_database_id = "R3PLY_DB"                     # Required for Pages local development

[[d1_databases]]
binding = "R3PLY_STAGING_DB"
database_name = "r3ply staging db"
database_id = "7ee88e89-bd64-41b8-bd03-a537ee600b4b"
preview_database_id = "R3PLY_STAGING_DB"

# This cleans up the pending comments every day at midnight
[triggers]
crons = ["0 0 * * *"]

# Docs: https://developers.cloudflare.com/email-routing/email-workers/send-email-workers/
[[send_email]]
name = "MODERATOR_EMAIL"
destination_address = "spence@admin.r3ply.com"

[[rules]]
type = "Text"
# Allow toml files to be read for reading r3ply system config
globs = ["**/*.toml"]
fallthrough = true

[[rules]]
type = "Text"
# Allow eml files to be read
globs = ["**/*.eml?raw"]
fallthrough = true
