version = "0.0.1"
domains = ["cli.r3ply.test"]
sites = ["site.local.test"]
enabled = true

[[admin]]
name = "Guybrush Threepwood"
email = "guybrush@example.com"

[email]
enabled = true
moderation = false
attachments = true
max_size_bytes = 5_242_880
block_list = []
