version = "0.0.1"
domain = "spenc.es"
r3ply = ['r3ply.com']

[comments.email]
"comment_{}" = "{{ comment.txt }}"
comment_separator = "﹍﹍﹍﹍﹍﹍﹍﹍﹍﹍﹍﹍﹍﹍﹍﹍﹍﹍﹍"

[comments.email.moderation]
type = 'github'
repo = "https://github.com/asimpletune/spenc.es"
# [Required] If you're using the `r3ply-github-bot` then specify the file path in the repo
# Templating is allowed here. The variables available are the same as the `template` field
"file_path_{}" = "content/comments/{{ comment.ts_rcvd }}_{{ comment.id_8 }}-{{ comment.author_7 }}.md"
"commit_msg_{}" = "viaEmail/github.commit.msg.txt"
"pr_title_{}" = "New comment from `{{ comment.id_8 }}`"
"pr_body_{}" = "viaEmail/github.pr.body.md"
"target_branch_{}" = "{{ comment.ts_rcvd }}_{{ comment.id_8 }}-{{ comment.author_7 }}.md"
