version = "0.0.1"
enabled = true

[[site]]
domain = "site.local.test"
r3ply = "cli.r3ply.test"
signet = "wWM5hk4DKr1xVRhVq-7aog"
issued = "2025-10-16"
label = "CLI"

[comments.email]
# "&comment_{}" = "templates/comment.md"

[[moderation.local]]
"file_path_{}" = "content/comments/{{ comment.id[:8] }}.json"
